version: '3.4'

services:
  movies_admin:
    container_name: movies_admin.interconnect
    build: app/
    env_file:
       - .env
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - interconnect
    
  postgres_to_es:
    container_name: postgres_to_es.interconnect
    build: postgres_to_es/
    env_file:
       - .env
    depends_on:
      - elasticsearch
    networks:
      - interconnect

  nginx:
    image: nginx:stable
    container_name: nginx.interconnect
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static-data:/data/static:ro
    ports:
      - 80:80
    depends_on:
      - movies_admin
    networks:
      - interconnect

  elasticsearch:
    image: docker.io/elastic/elasticsearch:7.7.0
    container_name: elasticsearch.interconnect
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - interconnect
    
  redis:
    image: redis:7.0.2-alpine
    container_name: redis.interconnect
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis-storage:/data
    networks:
      - interconnect

volumes:
  static-data:
    driver: local
  esdata: 
    driver: local
  redis-storage:
    driver: local

networks:
  interconnect:
    driver: bridge
